using System;
using System.Data;
using System.Data.SqlClient;
using SchoolManagementSystem.DAL;

namespace SchoolManagementSystem.BLL
{
    public class StudentService
    {
        public DataTable GetAllStudents()
        {
            return DatabaseHelper.ExecuteQuery("SELECT * FROM vw_FullStudentDetails");
        }

        public DataTable SearchStudents(string criterion)
        {
            string query = "SELECT * FROM vw_FullStudentDetails WHERE student_name LIKE @c OR reg_no LIKE @c OR class_name LIKE @c";
            SqlParameter[] parameters = { new SqlParameter("@c", "%" + criterion + "%") };
            return DatabaseHelper.ExecuteQuery(query, parameters);
        }

        public bool RegisterStudent(string name, DateTime birthday, int classId, string address, string mobile, int parentId)
        {
            // reg_no is auto-generated by computed column in DB
            string query = "INSERT INTO Student (name, birthday, class_id, address, mobile, parent_id) VALUES (@name, @dob, @cid, @addr, @mob, @pid)";
            SqlParameter[] parameters = {
                new SqlParameter("@name", name),
                new SqlParameter("@dob", birthday),
                new SqlParameter("@cid", classId),
                new SqlParameter("@addr", address),
                new SqlParameter("@mob", mobile),
                new SqlParameter("@pid", parentId)
            };
            return DatabaseHelper.ExecuteNonQuery(query, parameters) > 0;
        }
    }
}
